# Generated by Django 3.2.7 on 2021-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=256)),
                ('person', models.CharField(max_length=126)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
