# Generated by Django 3.2.7 on 2021-09-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="task",
        ),
    ]
