# Generated by Django 3.2.7 on 2021-09-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='added_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
